---
- name: Check Disk Space Usage
  hosts: all
  tasks:
          - name: Disk usage from command module
            ansible.builtin.command: df -h
             register: space
          - ansible.builtin.debug:
                  var: space
            
