- name: Check disk space on Linux machines
  hosts: localhosts
  gather_facts: yes

  tasks:
    - name: Display disk space
      shell: df -h
      register: disk_space
    - debug: var=disk_space.stdout_lines
